version: '3'

services:
  nodejs-backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PYTHON_SUMMARIZER_URL=http://python-summarizer:5000
    depends_on:
      - python-summarizer
    networks:
      - app-network

  python-summarizer:
    build:
      context: ./python-summarizer
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MODEL_NAME=t5-small
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
